# Configuration for ScWPSetup executed by setup.sh
#
# Author: Flurin Dürst » github.com/flurinduerst
# URL: https://github.com/flurinduerst/ScWPSetup
#
# Version: 1.3


# SETTINGS
##############################################################

locale: de_CH

# WordPress settings
settings:
  url: scwpsetup.dev
  title: Scotch WP Setup
  rewrite_structure: /%postname%/

# admin user settings
admin:
  user: admin
  password: admin
  email: admin@mail.com

# scotch box db access
db:
  name: scotchbox
  user: root
  pass: root
  prefix: wp_

# THEME
##############################################################

# theme to install
theme:
  name: WPSeed
  url: https://github.com/flurinduerst/WPSeed/archive/master.zip

# PLUGINS
##############################################################

# plugins to install & activate
plugins_active:
  - disable-comments
  - duplicate-post
  - enable-media-replace
  - favicon-by-realfavicongenerator
  - regenerate-thumbnails
  - simple-page-ordering
  - user-switching

# plugins to install
plugins_inactive:
  #development
  - regenerate-thumbnails
  - custom-post-type-ui
  - search-and-replace
  - capability-manager-enhanced
  - user-switching
  - favicon-by-realfavicongenerator
  - disable-comments
  #administration
  - adminimize
  - admin-menu-editor
  - admin-menu-reorder
  - enable-media-replace
  - duplicate-post
  - simple-page-ordering
  - wordpress-seo
  #security/backup
  - wp-security-audit-log
  - backwpup

# SETUP OPTIONS
##############################################################
# if you don't want the setup to run all tasks, you can
# set them to false

installation:
  wp: true
  theme: true
  cleanup: true
    comment: false
    posts: false
    files: false
    themes: true
  plugins: true
