# Configuration for WP Distillery executed by setup.sh
#
# Author: Flurin Dürst » github.com/flurinduerst
# URL: https://github.com/flurinduerst/WPDistillery
#
# File Version 1.42

# SETUP SETTINGS
#################################################################

# WordPress folder to execute the setup
wpfolder: public
wplocale: de_CH

# admin user settings
admin:
  user: admin
  password: admin
  email: admin@mail.com

# scotch box db access
db:
  name: scotchbox
  user: root
  pass: root
  prefix: wp_

# WORDPRESS SETTINGS
#################################################################

wpsettings:
  url: example.dev
  title: My Site
  rewrite_structure: /%postname%/

# THEME
#################################################################

# theme to install choose new name in 'rename' or leave empty
theme:
  name: WPSeed
  rename: ""
  url: https://github.com/flurinduerst/WPSeed/archive/master.zip

# PLUGINS
#################################################################

# plugins to install & activate
plugins_active:
  - disable-comments
  - duplicate-post
  - enable-media-replace
  - favicon-by-realfavicongenerator
  - regenerate-thumbnails
  - simple-page-ordering
  - user-switching

# plugins to install
plugins_inactive:
  #development
  - custom-post-type-ui
  - search-and-replace
  - capability-manager-enhanced
  - user-switching
  - favicon-by-realfavicongenerator
  - disable-comments
  #administration
  - adminimize
  - admin-menu-editor
  - admin-menu-reorder
  - enable-media-replace
  - duplicate-post
  - simple-page-ordering
  - wordpress-seo
  #security/backup
  - wp-security-audit-log
  - backwpup

# SETUP OPTIONS
####################################################################
# if you don't want the setup to run all tasks set them to false

installation:
  wp: true
  theme: true
  plugins: true
  cleanup: true
    comment: true
    posts: true
    files: true
    themes: true
